/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6GgaEV8wA3NAjSPNQQE37W
// Component: MM70zhLV8m-d

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { CmsRowField } from "@plasmicpkgs/plasmic-cms";
import ArrowBtn from "../../ArrowBtn"; // plasmic-import: sQwZRK4CPdyK/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "../blank_website/plasmic.module.css"; // plasmic-import: 6GgaEV8wA3NAjSPNQQE37W/projectcss
import sty from "./PlasmicPostCard.module.css"; // plasmic-import: MM70zhLV8m-d/css

createPlasmicElementProxy;

export type PlasmicPostCard__VariantMembers = {};
export type PlasmicPostCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicPostCard__VariantsArgs;
export const PlasmicPostCard__VariantProps = new Array<VariantPropType>();

export type PlasmicPostCard__ArgsType = {};
type ArgPropType = keyof PlasmicPostCard__ArgsType;
export const PlasmicPostCard__ArgProps = new Array<ArgPropType>();

export type PlasmicPostCard__OverridesType = {
  root?: Flex__<"div">;
  cardMediaFooter4?: Flex__<"div">;
  arrowBtn?: Flex__<typeof ArrowBtn>;
};

export interface DefaultPostCardProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPostCard__RenderFunc(props: {
  variants: PlasmicPostCard__VariantsArgs;
  args: PlasmicPostCard__ArgsType;
  overrides: PlasmicPostCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <CmsRowField
        className={classNames("__wab_instance", sty.cmsEntryField__eIkJ)}
        field={"image"}
        themeResetClassName={classNames(
          projectcss.root_reset,
          projectcss.root_reset_tags,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens
        )}
      />

      <CmsRowField
        className={classNames("__wab_instance", sty.cmsEntryField__gSpYk)}
        field={"title"}
        themeResetClassName={classNames(
          projectcss.root_reset,
          projectcss.root_reset_tags,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens
        )}
      />

      <CmsRowField
        className={classNames("__wab_instance", sty.cmsEntryField__qv65Z)}
        field={"description"}
        themeResetClassName={classNames(
          projectcss.root_reset,
          projectcss.root_reset_tags,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens
        )}
      />

      <Stack__
        as={"div"}
        data-plasmic-name={"cardMediaFooter4"}
        data-plasmic-override={overrides.cardMediaFooter4}
        hasGap={true}
        className={classNames(projectcss.all, sty.cardMediaFooter4)}
      >
        <ArrowBtn
          data-plasmic-name={"arrowBtn"}
          data-plasmic-override={overrides.arrowBtn}
          className={classNames("__wab_instance", sty.arrowBtn)}
        />
      </Stack__>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "cardMediaFooter4", "arrowBtn"],
  cardMediaFooter4: ["cardMediaFooter4", "arrowBtn"],
  arrowBtn: ["arrowBtn"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  cardMediaFooter4: "div";
  arrowBtn: typeof ArrowBtn;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPostCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPostCard__VariantsArgs;
    args?: PlasmicPostCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPostCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPostCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPostCard__ArgProps,
          internalVariantPropNames: PlasmicPostCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPostCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPostCard";
  } else {
    func.displayName = `PlasmicPostCard.${nodeName}`;
  }
  return func;
}

export const PlasmicPostCard = Object.assign(
  // Top-level PlasmicPostCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cardMediaFooter4: makeNodeComponent("cardMediaFooter4"),
    arrowBtn: makeNodeComponent("arrowBtn"),

    // Metadata about props expected for PlasmicPostCard
    internalVariantProps: PlasmicPostCard__VariantProps,
    internalArgProps: PlasmicPostCard__ArgProps
  }
);

export default PlasmicPostCard;
/* prettier-ignore-end */
