/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6GgaEV8wA3NAjSPNQQE37W
// Component: FfPpxlM_Ttcg

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 6GgaEV8wA3NAjSPNQQE37W/projectcss
import sty from "./PlasmicBtnWrp.module.css"; // plasmic-import: FfPpxlM_Ttcg/css

import ArrowRightIconWrapIcon from "./icons/PlasmicIcon__ArrowRightIconWrap"; // plasmic-import: 4HIycwZWkq14/icon

createPlasmicElementProxy;

export type PlasmicBtnWrp__VariantMembers = {};
export type PlasmicBtnWrp__VariantsArgs = {};
type VariantPropType = keyof PlasmicBtnWrp__VariantsArgs;
export const PlasmicBtnWrp__VariantProps = new Array<VariantPropType>();

export type PlasmicBtnWrp__ArgsType = {};
type ArgPropType = keyof PlasmicBtnWrp__ArgsType;
export const PlasmicBtnWrp__ArgProps = new Array<ArgPropType>();

export type PlasmicBtnWrp__OverridesType = {
  root?: Flex__<"div">;
  btnMainWrap?: Flex__<"div">;
  btnMainList?: Flex__<"div">;
  btnMainText?: Flex__<"div">;
  btnMainIcon?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultBtnWrpProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBtnWrp__RenderFunc(props: {
  variants: PlasmicBtnWrp__VariantsArgs;
  args: PlasmicBtnWrp__ArgsType;
  overrides: PlasmicBtnWrp__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"btnMainWrap"}
        data-plasmic-override={overrides.btnMainWrap}
        hasGap={true}
        className={classNames(projectcss.all, sty.btnMainWrap)}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"btnMainList"}
          data-plasmic-override={overrides.btnMainList}
          hasGap={true}
          className={classNames(projectcss.all, sty.btnMainList)}
        >
          <div
            data-plasmic-name={"btnMainText"}
            data-plasmic-override={overrides.btnMainText}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.btnMainText
            )}
          >
            {"Submit"}
          </div>
          {false ? (
            <div
              data-plasmic-name={"btnMainIcon"}
              data-plasmic-override={overrides.btnMainIcon}
              className={classNames(projectcss.all, sty.btnMainIcon)}
            >
              {false ? (
                <ArrowRightIconWrapIcon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                />
              ) : null}
            </div>
          ) : null}
        </Stack__>
      </Stack__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "btnMainWrap",
    "btnMainList",
    "btnMainText",
    "btnMainIcon",
    "svg"
  ],
  btnMainWrap: [
    "btnMainWrap",
    "btnMainList",
    "btnMainText",
    "btnMainIcon",
    "svg"
  ],
  btnMainList: ["btnMainList", "btnMainText", "btnMainIcon", "svg"],
  btnMainText: ["btnMainText"],
  btnMainIcon: ["btnMainIcon", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  btnMainWrap: "div";
  btnMainList: "div";
  btnMainText: "div";
  btnMainIcon: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBtnWrp__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBtnWrp__VariantsArgs;
    args?: PlasmicBtnWrp__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBtnWrp__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBtnWrp__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBtnWrp__ArgProps,
          internalVariantPropNames: PlasmicBtnWrp__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBtnWrp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBtnWrp";
  } else {
    func.displayName = `PlasmicBtnWrp.${nodeName}`;
  }
  return func;
}

export const PlasmicBtnWrp = Object.assign(
  // Top-level PlasmicBtnWrp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    btnMainWrap: makeNodeComponent("btnMainWrap"),
    btnMainList: makeNodeComponent("btnMainList"),
    btnMainText: makeNodeComponent("btnMainText"),
    btnMainIcon: makeNodeComponent("btnMainIcon"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicBtnWrp
    internalVariantProps: PlasmicBtnWrp__VariantProps,
    internalArgProps: PlasmicBtnWrp__ArgProps
  }
);

export default PlasmicBtnWrp;
/* prettier-ignore-end */
