/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6GgaEV8wA3NAjSPNQQE37W
// Component: 4Ad_NJbeLZ66

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariants_19VDikmmmbc3 } from "./PlasmicGlobalVariant__CloseStatesTabletMobile"; // plasmic-import: 19vDIKMMMBC3/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 6GgaEV8wA3NAjSPNQQE37W/projectcss
import sty from "./PlasmicFooter.module.css"; // plasmic-import: 4Ad_NJbeLZ66/css

import XIcon from "./icons/PlasmicIcon__X"; // plasmic-import: N8RCkXrJfqkc/icon
import IconLinkedinIcon from "./icons/PlasmicIcon__IconLinkedin"; // plasmic-import: PP3GYPb064wh/icon
import IconInstagramIcon from "./icons/PlasmicIcon__IconInstagram"; // plasmic-import: xgwB-7-vlDl4/icon
import IconFacebookIcon from "./icons/PlasmicIcon__IconFacebook"; // plasmic-import: ldXVlYSvmDJA/icon
import IconYoutubeIcon from "./icons/PlasmicIcon__IconYoutube"; // plasmic-import: kQezxP9GElPe/icon
import DividerIcon from "./icons/PlasmicIcon__Divider"; // plasmic-import: co9yA_WmmQ5x/icon

createPlasmicElementProxy;

export type PlasmicFooter__VariantMembers = {};
export type PlasmicFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooter__VariantsArgs;
export const PlasmicFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicFooter__ArgsType = {};
type ArgPropType = keyof PlasmicFooter__ArgsType;
export const PlasmicFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicFooter__OverridesType = {
  footer?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  footerLinkWrap?: Flex__<"div">;
  footerColumnWrap?: Flex__<"div">;
  footerListItem?: Flex__<"div">;
  footerListTitle?: Flex__<"div">;
  footerTitle?: Flex__<"div">;
  footerMenuWrap?: Flex__<"div">;
  navLinkItem?: Flex__<"div">;
  navLinkText?: Flex__<"div">;
  navLinkItem2?: Flex__<"div">;
  navLinkText2?: Flex__<"div">;
  navLinkItem3?: Flex__<"div">;
  navLinkText3?: Flex__<"div">;
  navLinkItem4?: Flex__<"div">;
  navLinkText4?: Flex__<"div">;
  navLinkItem5?: Flex__<"div">;
  navLinkText5?: Flex__<"div">;
  navLinkItem6?: Flex__<"div">;
  navLinkText6?: Flex__<"div">;
  footerColumnWrap2?: Flex__<"div">;
  footerListItem2?: Flex__<"div">;
  footerListTitle2?: Flex__<"div">;
  footerTitle2?: Flex__<"div">;
  footerMenuWrap2?: Flex__<"div">;
  navLinkItem7?: Flex__<"div">;
  navLinkText7?: Flex__<"div">;
  navLinkItem8?: Flex__<"div">;
  navLinkText8?: Flex__<"div">;
  footerColumnWrap3?: Flex__<"div">;
  footerListItem3?: Flex__<"div">;
  footerListTitle3?: Flex__<"div">;
  footerTitle3?: Flex__<"div">;
  footerMenuWrap3?: Flex__<"div">;
  navLinkItem9?: Flex__<"div">;
  navLinkText9?: Flex__<"div">;
  navLinkItem10?: Flex__<"div">;
  navLinkText10?: Flex__<"div">;
  navLinkItem11?: Flex__<"div">;
  navLinkText11?: Flex__<"div">;
  navLinkItem12?: Flex__<"div">;
  navLinkText12?: Flex__<"div">;
  navLinkItem13?: Flex__<"div">;
  navLinkText13?: Flex__<"div">;
  navLinkItem14?: Flex__<"div">;
  navLinkText14?: Flex__<"div">;
  footerColumnWrap4?: Flex__<"div">;
  footerListItem4?: Flex__<"div">;
  footerListTitle4?: Flex__<"div">;
  footerTitle4?: Flex__<"div">;
  footerMenuWrap4?: Flex__<"div">;
  navLinkItem15?: Flex__<"div">;
  navLinkText15?: Flex__<"div">;
  navLinkItem16?: Flex__<"div">;
  navLinkText16?: Flex__<"div">;
  footerColumnWrap5?: Flex__<"div">;
  footerContactWrap?: Flex__<"div">;
  contactContentWrap?: Flex__<"div">;
  socialIconsWrap?: Flex__<"div">;
  socialIconsList?: Flex__<"div">;
  socialIconItem?: Flex__<"div">;
  socialIconItem2?: Flex__<"div">;
  socialIconItem3?: Flex__<"div">;
  socialIconItem4?: Flex__<"div">;
  socialIconItem5?: Flex__<"div">;
  frame101692?: Flex__<"div">;
  footerLegalsWrap?: Flex__<"div">;
  legalsLinksList?: Flex__<"div">;
  legalLinkText?: Flex__<"div">;
  legalLinkText2?: Flex__<"div">;
  legalCopyrightText?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultFooterProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooter__RenderFunc(props: {
  variants: PlasmicFooter__VariantsArgs;
  args: PlasmicFooter__ArgsType;
  overrides: PlasmicFooter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    closeStatesTabletMobile: useScreenVariants_19VDikmmmbc3()
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"footer"}
      data-plasmic-override={overrides.footer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.footer
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"footerLinkWrap"}
          data-plasmic-override={overrides.footerLinkWrap}
          hasGap={true}
          className={classNames(projectcss.all, sty.footerLinkWrap)}
        >
          <Stack__
            as={"div"}
            data-plasmic-name={"footerColumnWrap"}
            data-plasmic-override={overrides.footerColumnWrap}
            hasGap={true}
            className={classNames(projectcss.all, sty.footerColumnWrap)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"footerListItem"}
              data-plasmic-override={overrides.footerListItem}
              hasGap={true}
              className={classNames(projectcss.all, sty.footerListItem)}
            >
              <div
                data-plasmic-name={"footerListTitle"}
                data-plasmic-override={overrides.footerListTitle}
                className={classNames(projectcss.all, sty.footerListTitle)}
              >
                <div
                  data-plasmic-name={"footerTitle"}
                  data-plasmic-override={overrides.footerTitle}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.footerTitle
                  )}
                >
                  {"About Us"}
                </div>
              </div>
              <div
                data-plasmic-name={"footerMenuWrap"}
                data-plasmic-override={overrides.footerMenuWrap}
                className={classNames(projectcss.all, sty.footerMenuWrap)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem"}
                  data-plasmic-override={overrides.navLinkItem}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem)}
                >
                  <div
                    data-plasmic-name={"navLinkText"}
                    data-plasmic-override={overrides.navLinkText}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText
                    )}
                  >
                    {"media"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem2"}
                  data-plasmic-override={overrides.navLinkItem2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem2)}
                >
                  <div
                    data-plasmic-name={"navLinkText2"}
                    data-plasmic-override={overrides.navLinkText2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText2
                    )}
                  >
                    {"our pillars"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem3"}
                  data-plasmic-override={overrides.navLinkItem3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem3)}
                >
                  <div
                    data-plasmic-name={"navLinkText3"}
                    data-plasmic-override={overrides.navLinkText3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText3
                    )}
                  >
                    {"climate, culture & Community"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem4"}
                  data-plasmic-override={overrides.navLinkItem4}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem4)}
                >
                  <div
                    data-plasmic-name={"navLinkText4"}
                    data-plasmic-override={overrides.navLinkText4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText4
                    )}
                  >
                    {"Executive Team"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem5"}
                  data-plasmic-override={overrides.navLinkItem5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem5)}
                >
                  <div
                    data-plasmic-name={"navLinkText5"}
                    data-plasmic-override={overrides.navLinkText5}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText5
                    )}
                  >
                    {"Careers"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem6"}
                  data-plasmic-override={overrides.navLinkItem6}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem6)}
                >
                  <div
                    data-plasmic-name={"navLinkText6"}
                    data-plasmic-override={overrides.navLinkText6}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText6
                    )}
                  >
                    {"Contact"}
                  </div>
                </Stack__>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"footerColumnWrap2"}
            data-plasmic-override={overrides.footerColumnWrap2}
            hasGap={true}
            className={classNames(projectcss.all, sty.footerColumnWrap2)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"footerListItem2"}
              data-plasmic-override={overrides.footerListItem2}
              hasGap={true}
              className={classNames(projectcss.all, sty.footerListItem2)}
            >
              <div
                data-plasmic-name={"footerListTitle2"}
                data-plasmic-override={overrides.footerListTitle2}
                className={classNames(projectcss.all, sty.footerListTitle2)}
              >
                <div
                  data-plasmic-name={"footerTitle2"}
                  data-plasmic-override={overrides.footerTitle2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.footerTitle2
                  )}
                >
                  {"Operations"}
                </div>
              </div>
              <div
                data-plasmic-name={"footerMenuWrap2"}
                data-plasmic-override={overrides.footerMenuWrap2}
                className={classNames(projectcss.all, sty.footerMenuWrap2)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem7"}
                  data-plasmic-override={overrides.navLinkItem7}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem7)}
                >
                  <div
                    data-plasmic-name={"navLinkText7"}
                    data-plasmic-override={overrides.navLinkText7}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText7
                    )}
                  >
                    {"Global Fleet"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem8"}
                  data-plasmic-override={overrides.navLinkItem8}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem8)}
                >
                  <div
                    data-plasmic-name={"navLinkText8"}
                    data-plasmic-override={overrides.navLinkText8}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText8
                    )}
                  >
                    {"Stats"}
                  </div>
                </Stack__>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"footerColumnWrap3"}
            data-plasmic-override={overrides.footerColumnWrap3}
            hasGap={true}
            className={classNames(projectcss.all, sty.footerColumnWrap3)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"footerListItem3"}
              data-plasmic-override={overrides.footerListItem3}
              hasGap={true}
              className={classNames(projectcss.all, sty.footerListItem3)}
            >
              <div
                data-plasmic-name={"footerListTitle3"}
                data-plasmic-override={overrides.footerListTitle3}
                className={classNames(projectcss.all, sty.footerListTitle3)}
              >
                <div
                  data-plasmic-name={"footerTitle3"}
                  data-plasmic-override={overrides.footerTitle3}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.footerTitle3
                  )}
                >
                  {"Technology"}
                </div>
              </div>
              <div
                data-plasmic-name={"footerMenuWrap3"}
                data-plasmic-override={overrides.footerMenuWrap3}
                className={classNames(projectcss.all, sty.footerMenuWrap3)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem9"}
                  data-plasmic-override={overrides.navLinkItem9}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem9)}
                >
                  <div
                    data-plasmic-name={"navLinkText9"}
                    data-plasmic-override={overrides.navLinkText9}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText9
                    )}
                  >
                    {"2pic by mara"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem10"}
                  data-plasmic-override={overrides.navLinkItem10}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem10)}
                >
                  <div
                    data-plasmic-name={"navLinkText10"}
                    data-plasmic-override={overrides.navLinkText10}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText10
                    )}
                  >
                    {"marafw"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem11"}
                  data-plasmic-override={overrides.navLinkItem11}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem11)}
                >
                  <div
                    data-plasmic-name={"navLinkText11"}
                    data-plasmic-override={overrides.navLinkText11}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText11
                    )}
                  >
                    {"mara slipstream"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem12"}
                  data-plasmic-override={overrides.navLinkItem12}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem12)}
                >
                  <div
                    data-plasmic-name={"navLinkText12"}
                    data-plasmic-override={overrides.navLinkText12}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText12
                    )}
                  >
                    {"Anduro"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem13"}
                  data-plasmic-override={overrides.navLinkItem13}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem13)}
                >
                  <div
                    data-plasmic-name={"navLinkText13"}
                    data-plasmic-override={overrides.navLinkText13}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText13
                    )}
                  >
                    {"Alys"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem14"}
                  data-plasmic-override={overrides.navLinkItem14}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem14)}
                >
                  <div
                    data-plasmic-name={"navLinkText14"}
                    data-plasmic-override={overrides.navLinkText14}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText14
                    )}
                  >
                    {"coordinate"}
                  </div>
                </Stack__>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"footerColumnWrap4"}
            data-plasmic-override={overrides.footerColumnWrap4}
            hasGap={true}
            className={classNames(projectcss.all, sty.footerColumnWrap4)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"footerListItem4"}
              data-plasmic-override={overrides.footerListItem4}
              hasGap={true}
              className={classNames(projectcss.all, sty.footerListItem4)}
            >
              <div
                data-plasmic-name={"footerListTitle4"}
                data-plasmic-override={overrides.footerListTitle4}
                className={classNames(projectcss.all, sty.footerListTitle4)}
              >
                <div
                  data-plasmic-name={"footerTitle4"}
                  data-plasmic-override={overrides.footerTitle4}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.footerTitle4
                  )}
                >
                  {"More"}
                </div>
              </div>
              <div
                data-plasmic-name={"footerMenuWrap4"}
                data-plasmic-override={overrides.footerMenuWrap4}
                className={classNames(projectcss.all, sty.footerMenuWrap4)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem15"}
                  data-plasmic-override={overrides.navLinkItem15}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem15)}
                >
                  <div
                    data-plasmic-name={"navLinkText15"}
                    data-plasmic-override={overrides.navLinkText15}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText15
                    )}
                  >
                    {"Investors"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"navLinkItem16"}
                  data-plasmic-override={overrides.navLinkItem16}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.navLinkItem16)}
                >
                  <div
                    data-plasmic-name={"navLinkText16"}
                    data-plasmic-override={overrides.navLinkText16}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.navLinkText16
                    )}
                  >
                    {"partnerships"}
                  </div>
                </Stack__>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"footerColumnWrap5"}
            data-plasmic-override={overrides.footerColumnWrap5}
            hasGap={true}
            className={classNames(projectcss.all, sty.footerColumnWrap5)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"footerContactWrap"}
              data-plasmic-override={overrides.footerContactWrap}
              hasGap={true}
              className={classNames(projectcss.all, sty.footerContactWrap)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"contactContentWrap"}
                data-plasmic-override={overrides.contactContentWrap}
                hasGap={true}
                className={classNames(projectcss.all, sty.contactContentWrap)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h8At
                  )}
                >
                  {"MARA\n101 NE 3rd Avenue #1200\nFort Lauderdale FL 33301"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rKk1Y
                  )}
                >
                  {"info@mara.com"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7BGTe
                  )}
                >
                  {"1.800.804.1690"}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"socialIconsWrap"}
                data-plasmic-override={overrides.socialIconsWrap}
                hasGap={true}
                className={classNames(projectcss.all, sty.socialIconsWrap)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"socialIconsList"}
                  data-plasmic-override={overrides.socialIconsList}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.socialIconsList)}
                >
                  <div
                    data-plasmic-name={"socialIconItem"}
                    data-plasmic-override={overrides.socialIconItem}
                    className={classNames(projectcss.all, sty.socialIconItem)}
                  >
                    <XIcon
                      className={classNames(projectcss.all, sty.svg__fi6YK)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"socialIconItem2"}
                    data-plasmic-override={overrides.socialIconItem2}
                    className={classNames(projectcss.all, sty.socialIconItem2)}
                  >
                    <IconLinkedinIcon
                      className={classNames(projectcss.all, sty.svg__vmwV4)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"socialIconItem3"}
                    data-plasmic-override={overrides.socialIconItem3}
                    className={classNames(projectcss.all, sty.socialIconItem3)}
                  >
                    <IconInstagramIcon
                      className={classNames(projectcss.all, sty.svg__l98Gh)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"socialIconItem4"}
                    data-plasmic-override={overrides.socialIconItem4}
                    className={classNames(projectcss.all, sty.socialIconItem4)}
                  >
                    <IconFacebookIcon
                      className={classNames(projectcss.all, sty.svg__fmFG)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"socialIconItem5"}
                    data-plasmic-override={overrides.socialIconItem5}
                    className={classNames(projectcss.all, sty.socialIconItem5)}
                  >
                    <IconYoutubeIcon
                      className={classNames(projectcss.all, sty.svg__fbCQm)}
                      role={"img"}
                    />
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
          </Stack__>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"frame101692"}
          data-plasmic-override={overrides.frame101692}
          hasGap={true}
          className={classNames(projectcss.all, sty.frame101692)}
        >
          <Stack__
            as={"div"}
            data-plasmic-name={"footerLegalsWrap"}
            data-plasmic-override={overrides.footerLegalsWrap}
            hasGap={true}
            className={classNames(projectcss.all, sty.footerLegalsWrap)}
          >
            <DividerIcon
              className={classNames(projectcss.all, sty.svg___4Mp8R)}
              role={"img"}
            />

            <Stack__
              as={"div"}
              data-plasmic-name={"legalsLinksList"}
              data-plasmic-override={overrides.legalsLinksList}
              hasGap={true}
              className={classNames(projectcss.all, sty.legalsLinksList)}
            >
              <div
                data-plasmic-name={"legalLinkText"}
                data-plasmic-override={overrides.legalLinkText}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.legalLinkText
                )}
              >
                {"Privacy policy"}
              </div>
              <div
                data-plasmic-name={"legalLinkText2"}
                data-plasmic-override={overrides.legalLinkText2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.legalLinkText2
                )}
              >
                {"Disclaimer"}
              </div>
            </Stack__>
            <div
              data-plasmic-name={"legalCopyrightText"}
              data-plasmic-override={overrides.legalCopyrightText}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.legalCopyrightText
              )}
            >
              {"\u00a9 2025 MARA Holdings, Inc. All rights reserved."}
            </div>
          </Stack__>
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"185px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(
                globalVariants,
                "closeStatesTabletMobile",
                "mobileOnly"
              )
                ? "auto"
                : "auto"
            }
            loading={"lazy"}
            src={{
              src: "/plasmic/blank_website/images/frame101694.svg",
              fullWidth: 886,
              fullHeight: 185,
              aspectRatio: 4.789189
            }}
          />
        </Stack__>
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  footer: [
    "footer",
    "freeBox",
    "footerLinkWrap",
    "footerColumnWrap",
    "footerListItem",
    "footerListTitle",
    "footerTitle",
    "footerMenuWrap",
    "navLinkItem",
    "navLinkText",
    "navLinkItem2",
    "navLinkText2",
    "navLinkItem3",
    "navLinkText3",
    "navLinkItem4",
    "navLinkText4",
    "navLinkItem5",
    "navLinkText5",
    "navLinkItem6",
    "navLinkText6",
    "footerColumnWrap2",
    "footerListItem2",
    "footerListTitle2",
    "footerTitle2",
    "footerMenuWrap2",
    "navLinkItem7",
    "navLinkText7",
    "navLinkItem8",
    "navLinkText8",
    "footerColumnWrap3",
    "footerListItem3",
    "footerListTitle3",
    "footerTitle3",
    "footerMenuWrap3",
    "navLinkItem9",
    "navLinkText9",
    "navLinkItem10",
    "navLinkText10",
    "navLinkItem11",
    "navLinkText11",
    "navLinkItem12",
    "navLinkText12",
    "navLinkItem13",
    "navLinkText13",
    "navLinkItem14",
    "navLinkText14",
    "footerColumnWrap4",
    "footerListItem4",
    "footerListTitle4",
    "footerTitle4",
    "footerMenuWrap4",
    "navLinkItem15",
    "navLinkText15",
    "navLinkItem16",
    "navLinkText16",
    "footerColumnWrap5",
    "footerContactWrap",
    "contactContentWrap",
    "socialIconsWrap",
    "socialIconsList",
    "socialIconItem",
    "socialIconItem2",
    "socialIconItem3",
    "socialIconItem4",
    "socialIconItem5",
    "frame101692",
    "footerLegalsWrap",
    "legalsLinksList",
    "legalLinkText",
    "legalLinkText2",
    "legalCopyrightText",
    "img"
  ],
  freeBox: [
    "freeBox",
    "footerLinkWrap",
    "footerColumnWrap",
    "footerListItem",
    "footerListTitle",
    "footerTitle",
    "footerMenuWrap",
    "navLinkItem",
    "navLinkText",
    "navLinkItem2",
    "navLinkText2",
    "navLinkItem3",
    "navLinkText3",
    "navLinkItem4",
    "navLinkText4",
    "navLinkItem5",
    "navLinkText5",
    "navLinkItem6",
    "navLinkText6",
    "footerColumnWrap2",
    "footerListItem2",
    "footerListTitle2",
    "footerTitle2",
    "footerMenuWrap2",
    "navLinkItem7",
    "navLinkText7",
    "navLinkItem8",
    "navLinkText8",
    "footerColumnWrap3",
    "footerListItem3",
    "footerListTitle3",
    "footerTitle3",
    "footerMenuWrap3",
    "navLinkItem9",
    "navLinkText9",
    "navLinkItem10",
    "navLinkText10",
    "navLinkItem11",
    "navLinkText11",
    "navLinkItem12",
    "navLinkText12",
    "navLinkItem13",
    "navLinkText13",
    "navLinkItem14",
    "navLinkText14",
    "footerColumnWrap4",
    "footerListItem4",
    "footerListTitle4",
    "footerTitle4",
    "footerMenuWrap4",
    "navLinkItem15",
    "navLinkText15",
    "navLinkItem16",
    "navLinkText16",
    "footerColumnWrap5",
    "footerContactWrap",
    "contactContentWrap",
    "socialIconsWrap",
    "socialIconsList",
    "socialIconItem",
    "socialIconItem2",
    "socialIconItem3",
    "socialIconItem4",
    "socialIconItem5",
    "frame101692",
    "footerLegalsWrap",
    "legalsLinksList",
    "legalLinkText",
    "legalLinkText2",
    "legalCopyrightText",
    "img"
  ],
  footerLinkWrap: [
    "footerLinkWrap",
    "footerColumnWrap",
    "footerListItem",
    "footerListTitle",
    "footerTitle",
    "footerMenuWrap",
    "navLinkItem",
    "navLinkText",
    "navLinkItem2",
    "navLinkText2",
    "navLinkItem3",
    "navLinkText3",
    "navLinkItem4",
    "navLinkText4",
    "navLinkItem5",
    "navLinkText5",
    "navLinkItem6",
    "navLinkText6",
    "footerColumnWrap2",
    "footerListItem2",
    "footerListTitle2",
    "footerTitle2",
    "footerMenuWrap2",
    "navLinkItem7",
    "navLinkText7",
    "navLinkItem8",
    "navLinkText8",
    "footerColumnWrap3",
    "footerListItem3",
    "footerListTitle3",
    "footerTitle3",
    "footerMenuWrap3",
    "navLinkItem9",
    "navLinkText9",
    "navLinkItem10",
    "navLinkText10",
    "navLinkItem11",
    "navLinkText11",
    "navLinkItem12",
    "navLinkText12",
    "navLinkItem13",
    "navLinkText13",
    "navLinkItem14",
    "navLinkText14",
    "footerColumnWrap4",
    "footerListItem4",
    "footerListTitle4",
    "footerTitle4",
    "footerMenuWrap4",
    "navLinkItem15",
    "navLinkText15",
    "navLinkItem16",
    "navLinkText16",
    "footerColumnWrap5",
    "footerContactWrap",
    "contactContentWrap",
    "socialIconsWrap",
    "socialIconsList",
    "socialIconItem",
    "socialIconItem2",
    "socialIconItem3",
    "socialIconItem4",
    "socialIconItem5"
  ],
  footerColumnWrap: [
    "footerColumnWrap",
    "footerListItem",
    "footerListTitle",
    "footerTitle",
    "footerMenuWrap",
    "navLinkItem",
    "navLinkText",
    "navLinkItem2",
    "navLinkText2",
    "navLinkItem3",
    "navLinkText3",
    "navLinkItem4",
    "navLinkText4",
    "navLinkItem5",
    "navLinkText5",
    "navLinkItem6",
    "navLinkText6"
  ],
  footerListItem: [
    "footerListItem",
    "footerListTitle",
    "footerTitle",
    "footerMenuWrap",
    "navLinkItem",
    "navLinkText",
    "navLinkItem2",
    "navLinkText2",
    "navLinkItem3",
    "navLinkText3",
    "navLinkItem4",
    "navLinkText4",
    "navLinkItem5",
    "navLinkText5",
    "navLinkItem6",
    "navLinkText6"
  ],
  footerListTitle: ["footerListTitle", "footerTitle"],
  footerTitle: ["footerTitle"],
  footerMenuWrap: [
    "footerMenuWrap",
    "navLinkItem",
    "navLinkText",
    "navLinkItem2",
    "navLinkText2",
    "navLinkItem3",
    "navLinkText3",
    "navLinkItem4",
    "navLinkText4",
    "navLinkItem5",
    "navLinkText5",
    "navLinkItem6",
    "navLinkText6"
  ],
  navLinkItem: ["navLinkItem", "navLinkText"],
  navLinkText: ["navLinkText"],
  navLinkItem2: ["navLinkItem2", "navLinkText2"],
  navLinkText2: ["navLinkText2"],
  navLinkItem3: ["navLinkItem3", "navLinkText3"],
  navLinkText3: ["navLinkText3"],
  navLinkItem4: ["navLinkItem4", "navLinkText4"],
  navLinkText4: ["navLinkText4"],
  navLinkItem5: ["navLinkItem5", "navLinkText5"],
  navLinkText5: ["navLinkText5"],
  navLinkItem6: ["navLinkItem6", "navLinkText6"],
  navLinkText6: ["navLinkText6"],
  footerColumnWrap2: [
    "footerColumnWrap2",
    "footerListItem2",
    "footerListTitle2",
    "footerTitle2",
    "footerMenuWrap2",
    "navLinkItem7",
    "navLinkText7",
    "navLinkItem8",
    "navLinkText8"
  ],
  footerListItem2: [
    "footerListItem2",
    "footerListTitle2",
    "footerTitle2",
    "footerMenuWrap2",
    "navLinkItem7",
    "navLinkText7",
    "navLinkItem8",
    "navLinkText8"
  ],
  footerListTitle2: ["footerListTitle2", "footerTitle2"],
  footerTitle2: ["footerTitle2"],
  footerMenuWrap2: [
    "footerMenuWrap2",
    "navLinkItem7",
    "navLinkText7",
    "navLinkItem8",
    "navLinkText8"
  ],
  navLinkItem7: ["navLinkItem7", "navLinkText7"],
  navLinkText7: ["navLinkText7"],
  navLinkItem8: ["navLinkItem8", "navLinkText8"],
  navLinkText8: ["navLinkText8"],
  footerColumnWrap3: [
    "footerColumnWrap3",
    "footerListItem3",
    "footerListTitle3",
    "footerTitle3",
    "footerMenuWrap3",
    "navLinkItem9",
    "navLinkText9",
    "navLinkItem10",
    "navLinkText10",
    "navLinkItem11",
    "navLinkText11",
    "navLinkItem12",
    "navLinkText12",
    "navLinkItem13",
    "navLinkText13",
    "navLinkItem14",
    "navLinkText14"
  ],
  footerListItem3: [
    "footerListItem3",
    "footerListTitle3",
    "footerTitle3",
    "footerMenuWrap3",
    "navLinkItem9",
    "navLinkText9",
    "navLinkItem10",
    "navLinkText10",
    "navLinkItem11",
    "navLinkText11",
    "navLinkItem12",
    "navLinkText12",
    "navLinkItem13",
    "navLinkText13",
    "navLinkItem14",
    "navLinkText14"
  ],
  footerListTitle3: ["footerListTitle3", "footerTitle3"],
  footerTitle3: ["footerTitle3"],
  footerMenuWrap3: [
    "footerMenuWrap3",
    "navLinkItem9",
    "navLinkText9",
    "navLinkItem10",
    "navLinkText10",
    "navLinkItem11",
    "navLinkText11",
    "navLinkItem12",
    "navLinkText12",
    "navLinkItem13",
    "navLinkText13",
    "navLinkItem14",
    "navLinkText14"
  ],
  navLinkItem9: ["navLinkItem9", "navLinkText9"],
  navLinkText9: ["navLinkText9"],
  navLinkItem10: ["navLinkItem10", "navLinkText10"],
  navLinkText10: ["navLinkText10"],
  navLinkItem11: ["navLinkItem11", "navLinkText11"],
  navLinkText11: ["navLinkText11"],
  navLinkItem12: ["navLinkItem12", "navLinkText12"],
  navLinkText12: ["navLinkText12"],
  navLinkItem13: ["navLinkItem13", "navLinkText13"],
  navLinkText13: ["navLinkText13"],
  navLinkItem14: ["navLinkItem14", "navLinkText14"],
  navLinkText14: ["navLinkText14"],
  footerColumnWrap4: [
    "footerColumnWrap4",
    "footerListItem4",
    "footerListTitle4",
    "footerTitle4",
    "footerMenuWrap4",
    "navLinkItem15",
    "navLinkText15",
    "navLinkItem16",
    "navLinkText16"
  ],
  footerListItem4: [
    "footerListItem4",
    "footerListTitle4",
    "footerTitle4",
    "footerMenuWrap4",
    "navLinkItem15",
    "navLinkText15",
    "navLinkItem16",
    "navLinkText16"
  ],
  footerListTitle4: ["footerListTitle4", "footerTitle4"],
  footerTitle4: ["footerTitle4"],
  footerMenuWrap4: [
    "footerMenuWrap4",
    "navLinkItem15",
    "navLinkText15",
    "navLinkItem16",
    "navLinkText16"
  ],
  navLinkItem15: ["navLinkItem15", "navLinkText15"],
  navLinkText15: ["navLinkText15"],
  navLinkItem16: ["navLinkItem16", "navLinkText16"],
  navLinkText16: ["navLinkText16"],
  footerColumnWrap5: [
    "footerColumnWrap5",
    "footerContactWrap",
    "contactContentWrap",
    "socialIconsWrap",
    "socialIconsList",
    "socialIconItem",
    "socialIconItem2",
    "socialIconItem3",
    "socialIconItem4",
    "socialIconItem5"
  ],
  footerContactWrap: [
    "footerContactWrap",
    "contactContentWrap",
    "socialIconsWrap",
    "socialIconsList",
    "socialIconItem",
    "socialIconItem2",
    "socialIconItem3",
    "socialIconItem4",
    "socialIconItem5"
  ],
  contactContentWrap: ["contactContentWrap"],
  socialIconsWrap: [
    "socialIconsWrap",
    "socialIconsList",
    "socialIconItem",
    "socialIconItem2",
    "socialIconItem3",
    "socialIconItem4",
    "socialIconItem5"
  ],
  socialIconsList: [
    "socialIconsList",
    "socialIconItem",
    "socialIconItem2",
    "socialIconItem3",
    "socialIconItem4",
    "socialIconItem5"
  ],
  socialIconItem: ["socialIconItem"],
  socialIconItem2: ["socialIconItem2"],
  socialIconItem3: ["socialIconItem3"],
  socialIconItem4: ["socialIconItem4"],
  socialIconItem5: ["socialIconItem5"],
  frame101692: [
    "frame101692",
    "footerLegalsWrap",
    "legalsLinksList",
    "legalLinkText",
    "legalLinkText2",
    "legalCopyrightText",
    "img"
  ],
  footerLegalsWrap: [
    "footerLegalsWrap",
    "legalsLinksList",
    "legalLinkText",
    "legalLinkText2",
    "legalCopyrightText"
  ],
  legalsLinksList: ["legalsLinksList", "legalLinkText", "legalLinkText2"],
  legalLinkText: ["legalLinkText"],
  legalLinkText2: ["legalLinkText2"],
  legalCopyrightText: ["legalCopyrightText"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  footer: "div";
  freeBox: "div";
  footerLinkWrap: "div";
  footerColumnWrap: "div";
  footerListItem: "div";
  footerListTitle: "div";
  footerTitle: "div";
  footerMenuWrap: "div";
  navLinkItem: "div";
  navLinkText: "div";
  navLinkItem2: "div";
  navLinkText2: "div";
  navLinkItem3: "div";
  navLinkText3: "div";
  navLinkItem4: "div";
  navLinkText4: "div";
  navLinkItem5: "div";
  navLinkText5: "div";
  navLinkItem6: "div";
  navLinkText6: "div";
  footerColumnWrap2: "div";
  footerListItem2: "div";
  footerListTitle2: "div";
  footerTitle2: "div";
  footerMenuWrap2: "div";
  navLinkItem7: "div";
  navLinkText7: "div";
  navLinkItem8: "div";
  navLinkText8: "div";
  footerColumnWrap3: "div";
  footerListItem3: "div";
  footerListTitle3: "div";
  footerTitle3: "div";
  footerMenuWrap3: "div";
  navLinkItem9: "div";
  navLinkText9: "div";
  navLinkItem10: "div";
  navLinkText10: "div";
  navLinkItem11: "div";
  navLinkText11: "div";
  navLinkItem12: "div";
  navLinkText12: "div";
  navLinkItem13: "div";
  navLinkText13: "div";
  navLinkItem14: "div";
  navLinkText14: "div";
  footerColumnWrap4: "div";
  footerListItem4: "div";
  footerListTitle4: "div";
  footerTitle4: "div";
  footerMenuWrap4: "div";
  navLinkItem15: "div";
  navLinkText15: "div";
  navLinkItem16: "div";
  navLinkText16: "div";
  footerColumnWrap5: "div";
  footerContactWrap: "div";
  contactContentWrap: "div";
  socialIconsWrap: "div";
  socialIconsList: "div";
  socialIconItem: "div";
  socialIconItem2: "div";
  socialIconItem3: "div";
  socialIconItem4: "div";
  socialIconItem5: "div";
  frame101692: "div";
  footerLegalsWrap: "div";
  legalsLinksList: "div";
  legalLinkText: "div";
  legalLinkText2: "div";
  legalCopyrightText: "div";
  img: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooter__VariantsArgs;
    args?: PlasmicFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFooter__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooter__ArgProps,
          internalVariantPropNames: PlasmicFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "footer") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("footer"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    footerLinkWrap: makeNodeComponent("footerLinkWrap"),
    footerColumnWrap: makeNodeComponent("footerColumnWrap"),
    footerListItem: makeNodeComponent("footerListItem"),
    footerListTitle: makeNodeComponent("footerListTitle"),
    footerTitle: makeNodeComponent("footerTitle"),
    footerMenuWrap: makeNodeComponent("footerMenuWrap"),
    navLinkItem: makeNodeComponent("navLinkItem"),
    navLinkText: makeNodeComponent("navLinkText"),
    navLinkItem2: makeNodeComponent("navLinkItem2"),
    navLinkText2: makeNodeComponent("navLinkText2"),
    navLinkItem3: makeNodeComponent("navLinkItem3"),
    navLinkText3: makeNodeComponent("navLinkText3"),
    navLinkItem4: makeNodeComponent("navLinkItem4"),
    navLinkText4: makeNodeComponent("navLinkText4"),
    navLinkItem5: makeNodeComponent("navLinkItem5"),
    navLinkText5: makeNodeComponent("navLinkText5"),
    navLinkItem6: makeNodeComponent("navLinkItem6"),
    navLinkText6: makeNodeComponent("navLinkText6"),
    footerColumnWrap2: makeNodeComponent("footerColumnWrap2"),
    footerListItem2: makeNodeComponent("footerListItem2"),
    footerListTitle2: makeNodeComponent("footerListTitle2"),
    footerTitle2: makeNodeComponent("footerTitle2"),
    footerMenuWrap2: makeNodeComponent("footerMenuWrap2"),
    navLinkItem7: makeNodeComponent("navLinkItem7"),
    navLinkText7: makeNodeComponent("navLinkText7"),
    navLinkItem8: makeNodeComponent("navLinkItem8"),
    navLinkText8: makeNodeComponent("navLinkText8"),
    footerColumnWrap3: makeNodeComponent("footerColumnWrap3"),
    footerListItem3: makeNodeComponent("footerListItem3"),
    footerListTitle3: makeNodeComponent("footerListTitle3"),
    footerTitle3: makeNodeComponent("footerTitle3"),
    footerMenuWrap3: makeNodeComponent("footerMenuWrap3"),
    navLinkItem9: makeNodeComponent("navLinkItem9"),
    navLinkText9: makeNodeComponent("navLinkText9"),
    navLinkItem10: makeNodeComponent("navLinkItem10"),
    navLinkText10: makeNodeComponent("navLinkText10"),
    navLinkItem11: makeNodeComponent("navLinkItem11"),
    navLinkText11: makeNodeComponent("navLinkText11"),
    navLinkItem12: makeNodeComponent("navLinkItem12"),
    navLinkText12: makeNodeComponent("navLinkText12"),
    navLinkItem13: makeNodeComponent("navLinkItem13"),
    navLinkText13: makeNodeComponent("navLinkText13"),
    navLinkItem14: makeNodeComponent("navLinkItem14"),
    navLinkText14: makeNodeComponent("navLinkText14"),
    footerColumnWrap4: makeNodeComponent("footerColumnWrap4"),
    footerListItem4: makeNodeComponent("footerListItem4"),
    footerListTitle4: makeNodeComponent("footerListTitle4"),
    footerTitle4: makeNodeComponent("footerTitle4"),
    footerMenuWrap4: makeNodeComponent("footerMenuWrap4"),
    navLinkItem15: makeNodeComponent("navLinkItem15"),
    navLinkText15: makeNodeComponent("navLinkText15"),
    navLinkItem16: makeNodeComponent("navLinkItem16"),
    navLinkText16: makeNodeComponent("navLinkText16"),
    footerColumnWrap5: makeNodeComponent("footerColumnWrap5"),
    footerContactWrap: makeNodeComponent("footerContactWrap"),
    contactContentWrap: makeNodeComponent("contactContentWrap"),
    socialIconsWrap: makeNodeComponent("socialIconsWrap"),
    socialIconsList: makeNodeComponent("socialIconsList"),
    socialIconItem: makeNodeComponent("socialIconItem"),
    socialIconItem2: makeNodeComponent("socialIconItem2"),
    socialIconItem3: makeNodeComponent("socialIconItem3"),
    socialIconItem4: makeNodeComponent("socialIconItem4"),
    socialIconItem5: makeNodeComponent("socialIconItem5"),
    frame101692: makeNodeComponent("frame101692"),
    footerLegalsWrap: makeNodeComponent("footerLegalsWrap"),
    legalsLinksList: makeNodeComponent("legalsLinksList"),
    legalLinkText: makeNodeComponent("legalLinkText"),
    legalLinkText2: makeNodeComponent("legalLinkText2"),
    legalCopyrightText: makeNodeComponent("legalCopyrightText"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
